apiVersion: v1
kind: ConfigMap
metadata:
  name: producer-config
  namespace: liveclass
data:
  # 클러스터 내부에서 Kafka Service 이름으로 접근
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  KAFKA_TOPIC: "liveclass-events"
